---
- name: create hosts file
  hosts: all
  tasks:
    - name: generate hosts file
      ansible.builtin.template:
        src: hosts.j2
        dest: /etc/hosts_v1
      when: inventory_hostname in groups ['dev']
