---
- name: creating lvm partition
  hosts: all
  tasks: 
    - name: if volume is not existed
      ansible.builtin.debug:
        msg: "vg not found"
      when: ansible_lvm.vgs.research is not defined
      
    - name: Create a lvm of 1500m
      community.general.lvol:
        vg: research
        lv: data
        size: '1500'
		  state: present
      when: ansible_lvm.vgs.research is defined and ansible_lvm.vgs.research.size_g > "1.5"
      
    - name: if 1500m volume is not available
      ansible.builtin.debug:
        msg: "Insufficient size of vg"
      when: ansible_lvm.vgs.research is defined and ansible_lvm.vgs.research.size_g < "1.5"
      
    - name: Create a lv of 800m
      community.general.lvol:
        vg: research
        lv: data
        size: '800'
		  state: present
      when: ansible_lvm.vgs.research is defined and ansible_lvm.vgs.research.size_g < "1.5"
      
    - name: create a file system with xfs format
      community.general.filesystem:
        fstype: ext4
        dev: /dev/research/data
      when: ansible_lvm.vgs.research is defined
