---
- name: creating users and groups
  hosts: all
  vars_files:
    - vault.yml
    - user_list.yml
  
  tasks:
    - name: creating groups
      ansible.builtin.group:
        name: "{{ item }}"
        state: present
      loop:
        - devops
        - opsmgr
    
    - name: create users for devops group
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ dev_pass | password_hash ('sha512') }}"
        groups: devops
        state: present
      loop: "{{ user }}"
      when: item.job == "developer" and (inventory_hostname in groups['dev'] or inventory_hostname in groups['balancers'] )

    - name: create users for opsmgr group
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ dev_pass | password_hash ('sha512') }}"
        groups: opsmgr
        state: present
      loop: "{{ user }}"
      when: item.job == "manager" and inventory_hostname in groups['prod']

